---
# tasks file for demo_app
  - name: Install webserver components
    apt:
      name: '{{ item }}'
      state: present
    with_items:
      - python-pip
      - python-virtualenv
      - python-mysqldb
    tags: [ 'packages' ]

  - name: copy demo app source
    copy:
      src: demo/app/
      dest: /var/www/demo
      mode: 0755
    notify: restart apache2
    tags: [ 'system config' ]

  - name: copy apache virtual host config
    copy:
      src: demo/demo.conf
      dest: /etc/apache2/sites-available
      mode: 0755
    notify: restart apache2
    tags: [ 'system config' ]

  - name: setup python virtualenv for the flask app
    pip:
      requirements: /var/www/demo/requirements.txt
      virtualenv: /var/www/demo/.venv
    notify: restart apache2
    tags: [ 'app config' ]

  - name: activate demo application site
    file:
      src: /etc/apache2/sites-available/demo.conf
      dest: /etc/apache2/sites-enabled/demo.conf
      state: link
    notify: restart apache2
    tags: [ 'app config' ]
