---
# tasks file for mysql
  - name: install required packages / tools
    apt:
      name: python-mysqldb
      state: present
      update_cache: yes

  - name: Install mysql
    apt:
      name: mysql-server
      state: present
      update_cache: yes
  - name: Check mysql
    service:
      name: mysql
      state: started
      enabled: yes
  - name: ensure mysql listening on all ports
    lineinfile:
      path: /etc/mysql/my.cnf
      regexp: '^bind-address'
      line: 'bind-address = {{ ansible_eth1.ipv4.address }}'
    notify: restart mysql

  - name: create demo database
    mysql_db:
      name: '{{ db_name }}'
      state: present

  - name: create database user
    mysql_user:
      name: '{{ db_user_name }}'
      password: '{{ db_user_pass }}'
      priv: '{{ db_name }}.*:ALL'
      host: '{{ db_user_host }}'
      state: present
